### PR TITLE
MNT: Replace master with main

### PR DESCRIPTION
**Pull request by pllim**
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.

This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

This is part of #66

### CODE REVIEW

**Comment by eteq** [comment]
Note I think I made the changes in this PR in the README in 5f4b69e750cb196b6e96b6f91a2071cd264512dc - sorry, @pllim, I didn't see this PR until *after* I did that! 

Note this also includes updates to the APE content.  But I'm realizing now that you've done this @pllim, that I'm not sure if this falls under the just-done "update" clause.  Which technically means @pllim  becomes a revision author.  And regardless technically it requires CoCo approval to update the text of APEs (but not the README).  So I see three options really:

1. Follow the normal revision process which means @pllim has to do some more changes here to reflect the revision of the documents, update Zenodo entries, etc
2. Don't bother because these are sort of "fixed time" documents - as long as the links still work that's probably OK.
3. Just say this fine and accept it.
 

Maybe @astrofrog or @taldcroft have opinions here?

**Review by eteq — CHANGES_REQUESTED** [review]
Note I think I made the changes in this PR in the README in 5f4b69e750cb196b6e96b6f91a2071cd264512dc - sorry, @pllim, I didn't see this PR until *after* I did that! 

Note though, that this PR also includes updates to the APE content.  But I'm realizing now that you've done this @pllim, that I'm not sure if this falls under the just-done "update" clause.  Which technically means @pllim  becomes a revision author.  And regardless technically it requires CoCo approval to update the text of APEs (but not the README).  So I see three options really:

1. Follow the normal revision process which means @pllim has to do some more changes here to reflect the revision of the documents, update Zenodo entries, etc
2. Don't bother because these are sort of "fixed time" documents - as long as the links still work that's probably OK.
3. Just say this fine and accept it.
 

Maybe @astrofrog or @taldcroft have opinions here?

**Comment by bsipocz** [comment]
> I'm not sure if this falls under the just-done "update" clause.

wouldn't this be on the level of typos? We had those fixed before without doing the update cycle and a round of approval. Basically there is no situation where these updates should be rejected...

**Comment by hamogu** [comment]
It seems that all the changes have been made (looking into the current `main` on the GH web interface). Is there a particular reason this PR is still open?

**Comment by pllim** [comment]
@eteq requested changes, so he should re-review.

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
